import { Link } from 'react-router-dom';
import { 
  SparklesIcon, 
  AcademicCapIcon, 
  ChartBarIcon, 
  UserGroupIcon,
  LightBulbIcon,
  ClockIcon,
  TrophyIcon,
  RocketLaunchIcon
} from '@heroicons/react/24/outline';

const HomePage = () => {
  const features = [
    {
      icon: SparklesIcon,
      title: 'AI-Powered Questions',
      description: 'Get unique, contextual questions generated by Google Gemini AI tailored to your learning needs.',
      color: 'from-purple-500 to-pink-500'
    },
    {
      icon: AcademicCapIcon,
      title: 'Multiple Subjects',
      description: 'Choose from 9+ subjects including Math, Science, History, Computer Science, and more.',
      color: 'from-blue-500 to-cyan-500'
    },
    {
      icon: ChartBarIcon,
      title: 'Track Your Progress',
      description: 'Comprehensive analytics and statistics to monitor your learning journey and improvement.',
      color: 'from-green-500 to-emerald-500'
    },
    {
      icon: TrophyIcon,
      title: 'Endless Mode',
      description: 'Challenge yourself with endless questions, compete on leaderboards, and earn streaks.',
      color: 'from-yellow-500 to-orange-500'
    }
  ];

  const steps = [
    {
      number: '01',
      title: 'Sign Up & Login',
      description: 'Create your free account in seconds. Secure authentication powered by Firebase ensures your data is safe.',
      icon: '🔐'
    },
    {
      number: '02',
      title: 'Configure Your Quiz',
      description: 'Select a subject, enter your topic, choose difficulty (Easy, Medium, Hard), and pick question count (5-20).',
      icon: '⚙️'
    },
    {
      number: '03',
      title: 'Take the Quiz',
      description: 'Answer AI-generated questions at your own pace. Navigate freely between questions and review your answers.',
      icon: '📝'
    },
    {
      number: '04',
      title: 'Review & Learn',
      description: 'Get instant results with detailed explanations for each answer. Track your progress over time.',
      icon: '📊'
    }
  ];

  const faqs = [
    {
      question: 'What is EduGlow?',
      answer: 'EduGlow is an AI-powered quiz generator that creates personalized quizzes using Google Gemini AI. It helps students learn and test their knowledge across multiple subjects with adaptive difficulty levels.'
    },
    {
      question: 'How does the AI generate questions?',
      answer: 'We use Google Gemini AI to generate unique, contextually relevant questions based on your selected topic and difficulty level. Each quiz is customized to ensure a fresh learning experience every time.'
    },
    {
      question: 'What subjects are available?',
      answer: 'EduGlow supports Mathematics, Science, History, Geography, Computer Science, Literature, Business, Art, and General Knowledge. You can enter any specific topic within these subjects.'
    },
    {
      question: 'Is EduGlow free to use?',
      answer: 'Yes! EduGlow is completely free to use. Simply sign up with your email and start generating unlimited quizzes.'
    },
    {
      question: 'What is Endless Mode?',
      answer: 'Endless Mode is a competitive game mode where you answer questions continuously. Each correct answer increases your streak, and your high score is displayed on the global leaderboard.'
    },
    {
      question: 'Can I review my past quizzes?',
      answer: 'Absolutely! All your quizzes are saved in your history. You can review questions, answers, and explanations anytime from your dashboard.'
    },
    {
      question: 'How are difficulty levels different?',
      answer: 'Easy questions cover fundamental concepts, Medium questions require deeper understanding, and Hard questions challenge you with complex scenarios and critical thinking.'
    },
    {
      question: 'Is my data secure?',
      answer: 'Yes! We use Firebase Authentication and Firestore with strict security rules. Your data is encrypted and only accessible to you.'
    }
  ];

  const stats = [
    { label: 'AI-Generated Questions', value: 'Unlimited', icon: SparklesIcon },
    { label: 'Subjects Available', value: '9+', icon: AcademicCapIcon },
    { label: 'Difficulty Levels', value: '3', icon: ChartBarIcon },
    { label: 'Active Learners', value: 'Growing', icon: UserGroupIcon }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-gray-50">
      {/* Navigation */}
      <nav className="bg-white shadow-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-3">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 220" className="w-10 h-10">
                <defs>
                  <linearGradient id="neonGradient" x1="0" y1="0" x2="1" y2="1">
                    <stop offset="0%" stopColor="#8B5CF6">
                      <animate attributeName="stop-color" values="#8B5CF6;#06B6D4;#22C55E;#8B5CF6" dur="5s" repeatCount="indefinite" />
                    </stop>
                    <stop offset="100%" stopColor="#06B6D4">
                      <animate attributeName="stop-color" values="#06B6D4;#22C55E;#8B5CF6;#06B6D4" dur="5s" repeatCount="indefinite" />
                    </stop>
                  </linearGradient>

                  <filter id="neonGlow" x="-40%" y="-40%" width="180%" height="180%">
                    <feGaussianBlur in="SourceGraphic" stdDeviation="8" result="blur"/>
                    <feMerge>
                      <feMergeNode in="blur"/>
                      <feMergeNode in="SourceGraphic"/>
                    </feMerge>
                  </filter>

                  <filter id="sparkGlow">
                    <feGaussianBlur stdDeviation="3" result="blur"/>
                    <feMerge>
                      <feMergeNode in="blur"/>
                      <feMergeNode in="SourceGraphic"/>
                    </feMerge>
                  </filter>
                </defs>

                <circle cx="110" cy="110" r="80" fill="none" stroke="url(#neonGradient)" strokeWidth="3" opacity="0.5">
                  <animate attributeName="r" values="78;84;78" dur="2s" repeatCount="indefinite" />
                  <animate attributeName="opacity" values="0.4;0.9;0.4" dur="2s" repeatCount="indefinite" />
                </circle>

                <circle cx="110" cy="110" r="60" fill="none" stroke="url(#neonGradient)" strokeWidth="4" opacity="0.9" strokeDasharray="10 8">
                  <animateTransform attributeName="transform" type="rotate" from="0 110 110" to="360 110 110" dur="5s" repeatCount="indefinite"/>
                </circle>

                <circle cx="110" cy="110" r="45" fill="url(#neonGradient)" filter="url(#neonGlow)" opacity="0.9">
                  <animate attributeName="r" values="44;46;44" dur="1.8s" repeatCount="indefinite" />
                </circle>

                <g transform="translate(110,110)">
                  <path d="M-25 -15q10 -5 25 0t25 0v25q-10 -5 -25 0t-25 0z" fill="white" opacity="0.2"/>
                  <path d="M-25 -10q10 -5 25 0t25 0M-25 2q10 -5 25 0t25 0" stroke="#E0F2FE" strokeWidth="2" strokeLinecap="round" opacity="0.9"/>
                </g>

                <path d="M110 20 L115 40 L108 40 L113 60" stroke="#FACC15" strokeWidth="2" fill="none" filter="url(#sparkGlow)">
                  <animate attributeName="opacity" values="0;1;0" dur="1s" repeatCount="indefinite"/>
                </path>
                <path d="M110 200 L105 180 L112 180 L107 160" stroke="#FACC15" strokeWidth="2" fill="none" filter="url(#sparkGlow)">
                  <animate attributeName="opacity" values="0;1;0" dur="1s" begin="0.5s" repeatCount="indefinite"/>
                </path>

                <g transform="translate(110,110)">
                  <animateTransform attributeName="transform" type="rotate" from="0" to="360" dur="12s" repeatCount="indefinite"/>
                </g>
              </svg>
              <span className="text-2xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                EduGlow
              </span>
            </div>
            <div className="flex items-center space-x-4">
              <Link
                to="/login"
                className="text-gray-700 hover:text-indigo-600 font-medium transition-colors"
              >
                Login
              </Link>
              <Link
                to="/signup"
                className="bg-gradient-to-r from-indigo-600 to-purple-600 text-white px-6 py-2 rounded-lg font-medium hover:shadow-lg transform hover:-translate-y-0.5 transition-all"
              >
                Get Started
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative overflow-hidden pt-20 pb-32">
        <div className="absolute inset-0 bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 opacity-70"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="inline-flex items-center space-x-2 bg-indigo-100 text-indigo-700 px-4 py-2 rounded-full text-sm font-medium mb-8 animate-pulse">
              <SparklesIcon className="w-4 h-4" />
              <span>Powered by Google Gemini AI</span>
            </div>
            <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold text-gray-900 mb-6">
              Learn Smarter with
              <span className="block bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 bg-clip-text text-transparent">
                AI-Generated Quizzes
              </span>
            </h1>
            <p className="text-xl text-gray-600 mb-10 max-w-3xl mx-auto leading-relaxed">
              Transform your learning experience with personalized quizzes created by artificial intelligence. 
              Choose your subject, set your difficulty, and start learning today.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                to="/signup"
                className="group bg-gradient-to-r from-indigo-600 to-purple-600 text-white px-8 py-4 rounded-xl font-semibold text-lg hover:shadow-2xl transform hover:-translate-y-1 transition-all flex items-center space-x-2"
              >
                <span>Start Learning Free</span>
                <RocketLaunchIcon className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Link>
              <a
                href="#how-it-works"
                className="bg-white text-gray-700 px-8 py-4 rounded-xl font-semibold text-lg hover:shadow-lg transform hover:-translate-y-1 transition-all border-2 border-gray-200"
              >
                See How It Works
              </a>
            </div>
          </div>

          {/* Stats */}
          <div className="mt-20 grid grid-cols-2 lg:grid-cols-4 gap-6">
            {stats.map((stat, index) => (
              <div
                key={index}
                className="bg-white rounded-2xl p-6 shadow-lg hover:shadow-xl transition-shadow text-center"
              >
                <stat.icon className="w-8 h-8 text-indigo-600 mx-auto mb-3" />
                <div className="text-3xl font-bold text-gray-900 mb-1">{stat.value}</div>
                <div className="text-sm text-gray-600">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Powerful Features for Better Learning
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Everything you need to enhance your learning experience in one place
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                className="group relative bg-gradient-to-br from-gray-50 to-white p-8 rounded-2xl border-2 border-gray-100 hover:border-transparent hover:shadow-2xl transition-all duration-300"
              >
                <div className={`absolute inset-0 bg-gradient-to-br ${feature.color} opacity-0 group-hover:opacity-5 rounded-2xl transition-opacity`}></div>
                <div className={`w-14 h-14 bg-gradient-to-br ${feature.color} rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform`}>
                  <feature.icon className="w-7 h-7 text-white" />
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-3">{feature.title}</h3>
                <p className="text-gray-600 leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section id="how-it-works" className="py-20 bg-gradient-to-br from-indigo-50 to-purple-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              How EduGlow Works
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Get started in four simple steps and begin your learning journey
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {steps.map((step, index) => (
              <div key={index} className="relative">
                {/* Connection Line */}
                {index < steps.length - 1 && (
                  <div className="hidden lg:block absolute top-20 left-full w-full h-0.5 bg-gradient-to-r from-indigo-300 to-purple-300"></div>
                )}
                
                <div className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-2xl transition-all duration-300 relative z-10">
                  <div className="text-6xl mb-4 text-center">{step.icon}</div>
                  <div className="text-sm font-bold text-indigo-600 mb-2">STEP {step.number}</div>
                  <h3 className="text-xl font-bold text-gray-900 mb-3">{step.title}</h3>
                  <p className="text-gray-600 leading-relaxed">{step.description}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="text-center mt-12">
            <Link
              to="/signup"
              className="inline-flex items-center space-x-2 bg-gradient-to-r from-indigo-600 to-purple-600 text-white px-8 py-4 rounded-xl font-semibold text-lg hover:shadow-2xl transform hover:-translate-y-1 transition-all"
            >
              <span>Start Your Journey</span>
              <RocketLaunchIcon className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </section>

      {/* Additional Features */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-4xl font-bold text-gray-900 mb-6">
                Why Choose EduGlow?
              </h2>
              <div className="space-y-6">
                <div className="flex items-start space-x-4">
                  <div className="w-12 h-12 bg-gradient-to-br from-green-500 to-emerald-500 rounded-lg flex items-center justify-center flex-shrink-0">
                    <LightBulbIcon className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-gray-900 mb-2">Smart Learning</h3>
                    <p className="text-gray-600">AI adapts to your learning style and generates questions that challenge you appropriately.</p>
                  </div>
                </div>
                
                <div className="flex items-start space-x-4">
                  <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-lg flex items-center justify-center flex-shrink-0">
                    <ClockIcon className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-gray-900 mb-2">Learn At Your Pace</h3>
                    <p className="text-gray-600">No time limits or pressure. Take quizzes whenever you want and review them anytime.</p>
                  </div>
                </div>
                
                <div className="flex items-start space-x-4">
                  <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-pink-500 rounded-lg flex items-center justify-center flex-shrink-0">
                    <ChartBarIcon className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-gray-900 mb-2">Track Progress</h3>
                    <p className="text-gray-600">Comprehensive analytics show your improvement over time with detailed statistics.</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="relative">
              <div className="absolute inset-0 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-3xl transform rotate-3"></div>
              <div className="relative bg-white rounded-3xl shadow-2xl p-8 transform -rotate-1">
                <div className="space-y-4">
                  <div className="flex items-center justify-between p-4 bg-gradient-to-r from-green-50 to-emerald-50 rounded-lg">
                    <span className="font-semibold text-gray-800">Quizzes Taken</span>
                    <span className="text-2xl font-bold text-green-600">50+</span>
                  </div>
                  <div className="flex items-center justify-between p-4 bg-gradient-to-r from-blue-50 to-cyan-50 rounded-lg">
                    <span className="font-semibold text-gray-800">Average Score</span>
                    <span className="text-2xl font-bold text-blue-600">85%</span>
                  </div>
                  <div className="flex items-center justify-between p-4 bg-gradient-to-r from-purple-50 to-pink-50 rounded-lg">
                    <span className="font-semibold text-gray-800">Current Streak</span>
                    <span className="text-2xl font-bold text-purple-600">7 Days</span>
                  </div>
                  <div className="flex items-center justify-between p-4 bg-gradient-to-r from-yellow-50 to-orange-50 rounded-lg">
                    <span className="font-semibold text-gray-800">Subjects Mastered</span>
                    <span className="text-2xl font-bold text-orange-600">5</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-20 bg-gradient-to-br from-gray-50 to-gray-100">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Frequently Asked Questions
            </h2>
            <p className="text-xl text-gray-600">
              Everything you need to know about EduGlow
            </p>
          </div>

          <div className="space-y-6">
            {faqs.map((faq, index) => (
              <details
                key={index}
                className="group bg-white rounded-xl shadow-md hover:shadow-lg transition-shadow overflow-hidden"
              >
                <summary className="flex items-center justify-between cursor-pointer p-6 font-semibold text-lg text-gray-900">
                  <span>{faq.question}</span>
                  <span className="text-indigo-600 group-open:rotate-180 transition-transform">
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  </span>
                </summary>
                <div className="px-6 pb-6 text-gray-600 leading-relaxed">
                  {faq.answer}
                </div>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-4xl font-bold text-white mb-6">
            Ready to Transform Your Learning?
          </h2>
          <p className="text-xl text-indigo-100 mb-10">
            Join thousands of students already learning smarter with AI-powered quizzes
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              to="/signup"
              className="bg-white text-indigo-600 px-8 py-4 rounded-xl font-bold text-lg hover:shadow-2xl transform hover:-translate-y-1 transition-all"
            >
              Get Started for Free
            </Link>
            <Link
              to="/login"
              className="bg-transparent border-2 border-white text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-white hover:text-indigo-600 transition-all"
            >
              Sign In
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-300 py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-3 gap-8 mb-8">
            <div>
              <div className="flex items-center space-x-3 mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 220" className="w-10 h-10">
                  <defs>
                    <linearGradient id="neonGradientFooter" x1="0" y1="0" x2="1" y2="1">
                      <stop offset="0%" stopColor="#8B5CF6">
                        <animate attributeName="stop-color" values="#8B5CF6;#06B6D4;#22C55E;#8B5CF6" dur="5s" repeatCount="indefinite" />
                      </stop>
                      <stop offset="100%" stopColor="#06B6D4">
                        <animate attributeName="stop-color" values="#06B6D4;#22C55E;#8B5CF6;#06B6D4" dur="5s" repeatCount="indefinite" />
                      </stop>
                    </linearGradient>

                    <filter id="neonGlowFooter" x="-40%" y="-40%" width="180%" height="180%">
                      <feGaussianBlur in="SourceGraphic" stdDeviation="8" result="blur"/>
                      <feMerge>
                        <feMergeNode in="blur"/>
                        <feMergeNode in="SourceGraphic"/>
                      </feMerge>
                    </filter>

                    <filter id="sparkGlowFooter">
                      <feGaussianBlur stdDeviation="3" result="blur"/>
                      <feMerge>
                        <feMergeNode in="blur"/>
                        <feMergeNode in="SourceGraphic"/>
                      </feMerge>
                    </filter>
                  </defs>

                  <circle cx="110" cy="110" r="80" fill="none" stroke="url(#neonGradientFooter)" strokeWidth="3" opacity="0.5">
                    <animate attributeName="r" values="78;84;78" dur="2s" repeatCount="indefinite" />
                    <animate attributeName="opacity" values="0.4;0.9;0.4" dur="2s" repeatCount="indefinite" />
                  </circle>

                  <circle cx="110" cy="110" r="60" fill="none" stroke="url(#neonGradientFooter)" strokeWidth="4" opacity="0.9" strokeDasharray="10 8">
                    <animateTransform attributeName="transform" type="rotate" from="0 110 110" to="360 110 110" dur="5s" repeatCount="indefinite"/>
                  </circle>

                  <circle cx="110" cy="110" r="45" fill="url(#neonGradientFooter)" filter="url(#neonGlowFooter)" opacity="0.9">
                    <animate attributeName="r" values="44;46;44" dur="1.8s" repeatCount="indefinite" />
                  </circle>

                  <g transform="translate(110,110)">
                    <path d="M-25 -15q10 -5 25 0t25 0v25q-10 -5 -25 0t-25 0z" fill="white" opacity="0.2"/>
                    <path d="M-25 -10q10 -5 25 0t25 0M-25 2q10 -5 25 0t25 0" stroke="#E0F2FE" strokeWidth="2" strokeLinecap="round" opacity="0.9"/>
                  </g>

                  <path d="M110 20 L115 40 L108 40 L113 60" stroke="#FACC15" strokeWidth="2" fill="none" filter="url(#sparkGlowFooter)">
                    <animate attributeName="opacity" values="0;1;0" dur="1s" repeatCount="indefinite"/>
                  </path>
                  <path d="M110 200 L105 180 L112 180 L107 160" stroke="#FACC15" strokeWidth="2" fill="none" filter="url(#sparkGlowFooter)">
                    <animate attributeName="opacity" values="0;1;0" dur="1s" begin="0.5s" repeatCount="indefinite"/>
                  </path>

                  <g transform="translate(110,110)">
                    <animateTransform attributeName="transform" type="rotate" from="0" to="360" dur="12s" repeatCount="indefinite"/>
                  </g>
                </svg>
                <span className="text-2xl font-bold text-white">EduGlow</span>
              </div>
              <p className="text-gray-400">
                AI-powered quiz generation for smarter learning and better results.
              </p>
            </div>
            
            <div>
              <h3 className="text-white font-bold mb-4">Quick Links</h3>
              <ul className="space-y-2">
                <li><a href="#how-it-works" className="hover:text-indigo-400 transition-colors">How It Works</a></li>
                <li><Link to="/signup" className="hover:text-indigo-400 transition-colors">Sign Up</Link></li>
                <li><Link to="/login" className="hover:text-indigo-400 transition-colors">Login</Link></li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-white font-bold mb-4">Powered By</h3>
              <ul className="space-y-2 text-gray-400">
                <li>Google Gemini AI</li>
                <li>Firebase</li>
                <li>React & Tailwind CSS</li>
              </ul>
            </div>
          </div>
          
          <div className="border-t border-gray-800 pt-8 text-center text-gray-400">
            <p>&copy; 2025 EduGlow. Built with ❤️ for learners everywhere.</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default HomePage;
